# Generated by Django 2.2.9 on 2020-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_auto_20200725_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
