# Generated by Django 2.2.9 on 2020-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_auto_20200823_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
