# Generated by Django 2.2.6 on 2020-09-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0014_auto_20200910_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="author",
            field=models.ForeignKey(
                default="0000000",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="На кого подписался",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                default="0000000",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подписался",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "author")},
        ),
    ]
