version: '3.9'
# instruction at the end of file

volumes:
  db:
  static:
  media:
  nginx_conf:

services:
  django:
    image: matakov/matacoders:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/code/static
      - db:/code/db
      - media:/code/media
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh
    environment:
      - DEBUG=0

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always
