version: '3.9'

services:

  django:
    build: .
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/code/
    entrypoint: /code/entrypoint.sh
    environment:
      - DEBUG=1

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always